apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress
type: Opaque
data:
  mysql-user: d29yZHByZXNz   # Base64 encoded "wordpress"
  mysql-password: d29yZHByZXNzUGFzc3dvcmQ=  # Base64 encoded "wordpressPassword"
