apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  mariadb-user: d29yZHByZXNzX3VzZXI=
  mariadb-password: bXlwYXNzd29yZA==
  mariadb-name: d29yZHByZXNzX2Ri
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-admin-secret
type: Opaque
stringData:
  wp-admin-user: Gom@thi7777
  wp-admin-password: CYuUf1f4d7UE7J*!lY
  wp-admin-email: admin@example.com
  wp-site-title: boss
  wp-site-url: http://10.184.49.243:31282/wordpress
