apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mariadb-service
subsets:
  - addresses:
      - ip: 10.184.49.241
    ports:
      - port: 3306
