apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress
type: Opaque
data:
  mariadb-user: d29yZHByZXNzX3VzZXI=
  mariadb-password: bXlwYXNzd29yZA==
  mariadb-name: d29yZHByZXNzX2Ri

