apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress  # Ensure all resources are in the same namespace
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data  # Ensure this path is available on your nodes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: wordpress  # Added namespace to match Deployment
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Ensure it matches PV
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
  namespace: wordpress
type: Opaque
data:
  DB_NAME: d29yZHByZXNzX2Ri   # base64 encoded 'wordpress_db'
  DB_USER: d29yZHByZXNzX3VzZXI=  # base64 encoded 'wordpress_user'
  DB_PASSWORD: bXlwYXNzd29yZA==  # base64 encoded 'mypassword'
  DB_HOST: MTAuMTg0LjQ5LjI0MQ==  # base64 encoded '10.184.49.241'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: gomathi747/wordpress-docker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: DB_HOST
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
