---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31211
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  volumeMode: Filesystem
  local:
    path: /var/www/html/wordpress
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8snewmaster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8snewmaster
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      initContainers:
        - name: init-wordpress
          image: gomathi747/wordpress:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              git config --global --add safe.directory /var/www/html/wordpress
              if [ ! -d "/var/www/html/wordpress/.git" ]; then
                rm -rf /var/www/html/wordpress/*
                git clone --depth=1 --branch main https://github.com/NarpaviGomathi/WordPress.git /var/www/html/wordpress
              else
                cd /var/www/html/wordpress
                git reset --hard
                git clean -fd
                git pull origin main
              fi

              rm -f /var/www/html/wordpress/wp-config.php

              chown -R www-data:www-data /var/www/html/wordpress
              chmod -R 755 /var/www/html/wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html/wordpress

      containers:
        - name: wordpress
          image: gomathi747/wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "10.184.49.241"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-name
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html/wordpress

      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
