apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: gomathi747/wordpress-docker:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_NAME
              value: "wordpress_db"
            - name: DB_USER
              value: "wordpress_user"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_HOST
              value: "10.184.49.241"  # Change this to your actual DB host
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
      volumes: []

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Change to NodePort if needed
