---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: rook-ceph-block  # Make sure this exists
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      initContainers:
        - name: init-wordpress
          image: gomathi747/wordpress:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "🔁 Syncing Git repo to persistent storage..."
              if [ ! -d "/var/www/html/wordpress/.git" ]; then
                rm -rf /var/www/html/wordpress/*
                git clone --depth=1 --branch main https://github.com/NarpaviGomathi/WordPress.git /var/www/html/wordpress
              else
                cd /var/www/html/wordpress && git pull origin main
              fi
              chown -R www-data:www-data /var/www/html/wordpress
              chmod -R 755 /var/www/html/wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html

      containers:
        - name: wordpress
          image: gomathi747/wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "10.184.49.241"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-name
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html

      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
