---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31282
  selector:
    app: wordpress
    tier: frontend

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      initContainers:
        - name: init-wordpress
          image: gomathi747/wordpress:latest
          command: ["/bin/bash", "-c"]
          env:
            - name: DB_HOST
              value: "10.184.49.241"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-name
            - name: WP_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-admin-secret
                  key: wp-admin-user
            - name: WP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-admin-secret
                  key: wp-admin-password
            - name: WP_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: wordpress-admin-secret
                  key: wp-admin-email
            - name: WP_SITE_TITLE
              valueFrom:
                secretKeyRef:
                  name: wordpress-admin-secret
                  key: wp-site-title
            - name: WP_SITE_URL
              valueFrom:
                secretKeyRef:
                  name: wordpress-admin-secret
                  key: wp-site-url
          args:
            - |
              set -e
              git config --global --add safe.directory /var/www/html/wordpress
              if [ ! -d "/var/www/html/wordpress/.git" ]; then
                rm -rf /var/www/html/wordpress/*
                git clone --depth=1 --branch main https://github.com/NarpaviGomathi/WordPress.git /var/www/html/wordpress
              else
                cd /var/www/html/wordpress 
                git reset --hard
                git clean -fd
                git pull origin main
              fi
              
              rm -f /var/www/html/wordpress/wp-config.php

              cd /var/www/html/wordpress
              
              cp wp-config-sample.php wp-config.php
              sed -i "s/database_name_here/${DB_NAME}/" wp-config.php
              sed -i "s/username_here/${DB_USER}/"       wp-config.php
              sed -i "s/password_here/${DB_PASSWORD}/"   wp-config.php
              sed -i "s/localhost/${DB_HOST}/"           wp-config.php
              sed -i "/define( 'WP_DEBUG', false );/d"   wp-config.php
              echo "define( 'WP_DEBUG', true );"       >> wp-config.php
              if ! grep -q "define( 'FS_METHOD', 'direct' );" wp-config.php; then
                echo "define( 'FS_METHOD', 'direct' );"     >> wp-config.php
              fi
              sed -i "s|^\$table_prefix = .*|\$table_prefix = 'wp_';|" wp-config.php

              chown www-data:www-data wp-config.php && chmod 644 wp-config.php
              chown -R www-data:www-data /var/www/html/wordpress
              chmod -R 755 /var/www/html/wordpress

              echo " Waiting for database to be ready..."
              until wp db check --path=/var/www/html/wordpress --allow-root; do
                echo "Waiting..."
                sleep 5
              done

              if ! wp core is-installed --path=/var/www/html/wordpress --allow-root; then
                echo "Installing WordPress..."
                wp core install \
                  --url="${WP_SITE_URL}" \
                  --title="${WP_SITE_TITLE}" \
                  --admin_user="${WP_ADMIN_USER}" \
                  --admin_password="${WP_ADMIN_PASSWORD}" \
                  --admin_email="${WP_ADMIN_EMAIL}" \
                  --path=/var/www/html/wordpress \
                  --allow-root
              else
                echo "WordPress already installed."
              fi
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html/wordpress

      containers:
        - name: wordpress
          image: gomathi747/wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "10.184.49.241"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-name
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html/wordpress

      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
